tc39/proposal-async-context

- .github/workflows/test.yml
- package-lock.json
- package.json
- src/fork.ts
- src/index.ts
- src/mapping.ts
- src/storage.ts
- tests/async-context.test.ts
- tsconfig.json
Currently, every time `run()` is called, we clone the underlying storage `Map`. This is done so that the the modification will not change a map which is held by a `wrap`'s snapshot. I believe "wrapping" (either explicitly with `AsyncContext.wrap()` or implicitly through `Promise`s) will be performed 10000x more times in a normal program than `run()`, so I'm doing everything possible to make the `wrap()` method as fast as possible. Further, that `get()` will be called at least at much and probably more as `run()`. So my priorities are:
- `wrap()` **must be `O(1)`** (and ideally require nothing more than a pointer reference)
- `get()` should be as fast as possible
- `run()` may be slow, but let's try to make it fast
These priorities lead to code that causes quadratic cloning of the …
> Optimize run to avoid quadratic map cloning

- package-lock.json
- package.json
- spec.html
This is the initial spec draft of the proposal. It follows the (tentative) idea of:
1. The async context storage is a per-agent setting.
2. https://github.com/tc39/proposal-async-context/issues/16: `HostPromiseRejectionTracker` is called in the context at the time of the promise's rejection.
> Initial spec draft

- spec.html
`AsyncContext.wrap` should create a wrapped function when the target is callable, and copy the length and name property if possible.
> Type check in AsyncContext.wrap

- README.md
This change updates the explainer to not list Prioritized Task Scheduling as a browser-internal use case, since it can be used together with `AsyncContext` as the former API is currently defined. The browser-internal use case (transitive task prioritization) is also listed, together with it.
This change also removes the browser-internal use case of limiting access to certain APIs, since it was felt to be somewhat controversial.
> Update the use cases in the explainer's motivation section

- README.md
based on this code below with `await` we're expecting to return a value here:
```typescript
const res = await scheduler.postTask(task, { priority: "background" });
```
> Add missing return to README example

- README.md
- SCOPING.md
- spec.html
To distinguish the abstraction around the global state and local state, replace the built-in class `AsyncContext` with `AsyncContext.Snapshot` and `AsyncContext.Variable`.
Fixes: https://github.com/tc39/proposal-async-context/issues/44
Fixes: https://github.com/tc39/proposal-async-context/issues/36
Fixes: https://github.com/tc39/proposal-async-context/issues/21
> Add AsyncContext namespace and Snapshot and Variable

- .vscode/settings.json
- spec.html
> Make sync and async generators restore the initialization context

- README.md
- USE-CASES.md
Expanding on the use cases regarding the actions of the May 3rd call.
> Expand use cases document

- README.md
Distinguish Snapshot's use case with Variable's. And add a FAQ section for the function parameters in `run`.
> Expand on Snapshot and the function parameter

- README.md
- SNAPSHOT.md
Expand on the requirements of `AsyncContext.Snapshot` and the alternatives.
> Expand on requirements of Snapshot

- README.md
Is this a typo in the comment here? Maybe `implicit` used to be named `indirect`?
> README typo?

- spec.html
> Make sure to propagate a promise job's snapshot when handling abrupt completions

- spec.html
Based on our last meeting, we'll only preserve the ambient AC state for user created generators. Spec created generators, used during iteration and async iteration, do not need to preserve the context. It would only be observable during iteration of `array.values()` with a getter.
Note that the if the user uses async iteration of of a spec-created generator, then their context will be preserved in _their_ execution:
```js
const array = [];
Object.defineProperty(array, 0, {
get() {
// This used to be "foo", the iterator captured ambient AC during init.
assert.sameValue(asyncVar.get(), "bar");
}
});
const iter = asyncVar.run("foo", () => array.values());
asyncVar.run("bar", () => {
iter.next();
});
```
> Only preserve AC for user generators

- package-lock.json
- package.json
- spec.html
This snapshots the ambient AC state when calling `fr.register()`, to be restored when invoking the FR's callback on that registered cell.
- - -
I also removed our changes of `HostMakeJobCallback`. First, because it felt awkward to refer to the `JobCallback`'s `[[AsyncContextSnapshot]]` inside `NewPromiseReactionJob` and `NewPromiseResolveThenableJob`. And second, because it actually causes a memory leak with `FinalizationRegistry`.
The FR calls `HostMakeJobCallback` (causing it to snapshot) during its constructor to prepare the callback to be used for jobs later on. But that snapshot will never be used, we'll only use the registration time snapshot. So I had to move the snapshotting closer into `PerformPromiseThen`.
> Handle FinalizationRegistry

- spec.html
Fixes: https://github.com/tc39/proposal-async-context/pull/86#issuecomment-2093235894
> Editorial: fix SetFunctionName assertion

- spec.html
In the web integration of AsyncContext, web specs will need to create `AsyncContext.Snapshot` objects from an AsyncContext mapping; and we expect this to be necessary for other kinds of hosts as well, such as Node.js.
Currently the spec text does not provide any way to do that other than manually creating the object and populating its
`[[AsyncContextMapping]]` slot, since the `AsyncContext.Snapshot` constructor always uses the current mapping. So this patch adds an abstract operation called `CreateAsyncContextSnapshot` that provides this capability.
> Add `CreateAsyncContextSnapshot` AO

- CONTINUATION.md
Document the discussed semantics of continuation flow.
/cc @Qard please feel free to suggest correction of the semantics since many of the details were not expanded.
Closes https://github.com/tc39/proposal-async-context/issues/83
> Add continuation flow doc

- spec.html
Fixes https://github.com/tc39/proposal-async-context/issues/73
> Editorial: unify term async context mapping

- MUTATION-SCOPE.md
Compare `run` and set semantic (`@@enter` and `@@dispose`), and an example that could potentially be implemented on `AsyncContext` with set semantic:
```js
async function doWork() {
using parent = tracer.startAsCurrentSpan("parent");
// do some work that 'parent' tracks
console.log("doing some work...");
// Create a nested span to track nested work
{
using child = tracer.startAsCurrentSpan("child");
// do some work that 'child' tracks
console.log("doing some nested work...")
// the nested span is closed when it's out of scope
}
// This parent span is also closed when it goes out of scope
}
```
> Add mutation explainer

- spec.html
Each FinalizationRegistry object has a context associated with it, which was the context at its construction. This context is used for calling its callback when any registered object is GC'd, which takes place in the `CleanupFinalizationRegistry` AO.
In the current spec, `CleanupFinalizationRegistry` handles the swapping of this context, and restores it back at the end. This, however, causes a problem for hosts that report uncaught JS exceptions by running JS code (such as the `"error"` event on `window` in the web, or the `"unhandledException"` event on `process` in Node.js), since they should run this event in the FinalizationRegistry's creation context, but `CleanupFinalizationRegistry` exits that context before the end of the function.
Since `CleanupFinalizationRegistry` (and …
> Handle the FinalizationRegistry's context in `HostEnqueueFinalizationRegistryCleanupJob`

- MEMORY-MANAGEMENT.md
- WEB-INTEGRATION.md
This patch also adds a few clarifications and fixes to the web integration document.
cc @smaug----
> Add memory management document

- FRAMEWORKS.md
- USE-CASES.md
Marking as draft because we are still waiting on a quote-style explanation from React & Angular.
They are all sorted alphabetically, because I tried choosing which framework is the best to put it first and failed 😛
> Add frameworks use cases

- FRAMEWORKS.md
Fix the formatting of my comment re React
> Fix formatting in FRAMEWORKS.md

- WEB-INTEGRATION.md
This copies the discussion from https://github.com/tc39/proposal-async-context/issues/107 and from the bi-weekly calls into a document we can more easily share.
Let's keep the issue open so that discussion can stay there.
> Expand on the fallback context in web integration

- WEB-INTEGRATION.md
I was reading through the web integration doc again, and changed some parts to highlight more the core design aspects and the reason behind them. Importantly, I added the same observations that there are in the slides for the upcoming TC39 meeting:
- the proposed behavior matches what you would usually get from userland implementations
- in many cases there is no difference between dispatch and causal contexts.
I also changed the note about Observers, marking that as Important using GitHub's syntax (https://github.com/orgs/community/discussions/16925), explaining why going through the always-empty-context path can be explained as coherent.
> Clarify a bit web integration document

- WEB-INTEGRATION.md
@andreubotella Do you think this should say more?
> web integration: Add note about cross-origin same-agent functions

- USE-CASES.md
I haven't seen this discussed elsewhere, so thought it might be a worthwhile addition to USE-CASES.md: modern SSR frameworks can in theory run wherever JavaScript does, but since most nowadays use `AsyncLocalStorage`, 'wherever JavaScript does' doesn't include service workers.
This is a loss to the web, since there are certainly apps that would benefit from this approach.
> add service worker use case

- USE-CASES.md
I've noticed the use cases docs reference `AsyncContext` as if it was `AsyncContext.Variable`, but did not find easily any place in the spec that specifies that this is allowed.
Hence, this change updates the references of `new AsyncContext()` to `new AsyncContext.Variable()` to match the convention of the other examples.
> chore: fix instantiation of async context to use variable in use cases

- MEMORY-MANAGEMENT.md
Github's Markdown renderer does not seem to support custom heading IDs.
> Remove ID from "The context as a weak map" heading
